.github/workflows/testing.yml

Resolves #39 
[CONTRIBUTING.rst](https://github.com/icaros-usc/pyribs/blob/master/CONTRIBUTING.rst).
errors)

Enable 3.7/3.8 in CI/CD

---

Makefile
docs/examples.md
docs/examples/lunar_lander.md
examples/lunar_lander.py
examples/sphere.py
examples/tutorials/lunar_lander.ipynb
setup.py
tests/examples.sh

Though we have the lunar lander tutorial, we should have a lunar lander example that includes Dask usage. This commit adds back and finalizes the example.
Resolves #69 

Finish Lunar Lander Example

---

README.md
docs/_static/custom.css
examples/README.md

PR for accumulating documentation fixes.

More documentation fixes

---

ribs/emitters/opt/_cma_es.py
tests/core/emitters/cma_me_emitter_test.py

This resolves a bug where if the `GridArchive` has `dtype=float32`, the CMA-ME emitters fail due to a bug in `CMAEvolutionStrategy`.
Fix a bug where CMA-ME emitters do not work with float32 archives

Enable CMA-ME emitters to work with float32

---

examples/sphere.py

Miscellaneous edits for the Sphere example. Came across these while creating the video for the website.
Added nicer figures to the Sphere example with `grid_archive_heatmap`

Sphere example edits

---

HISTORY.md
ribs/__init__.py
setup.cfg
setup.py

v0.3.1 release

---

ribs/archives/_cvt_archive.py
ribs/visualize.py
tests/core/archives/cvt_archive_test.py

Rename index to index_0 in CVTArchive.as_pandas

---

tests/core/archives/archive_base_test.py
tests/core/archives/cvt_archive_test.py
tests/core/archives/grid_archive_test.py
tests/core/archives/sliding_boundaries_archive_test.py

Moved the as_pandas tests into the ArchiveBase tests, and added tests for the metadata.
Refactor as_pandas tests and test metadata (#114)

Refactor as_pandas tests and test metadata

---

ribs/emitters/_emitter_base.py
ribs/emitters/_improvement_emitter.py
ribs/emitters/_optimizing_emitter.py
ribs/emitters/_random_direction_emitter.py
ribs/optimizers/_optimizer.py
tests/core/emitters/conftest.py
tests/core/emitters/emitter_base_test.py
tests/core/optimizers/optimizer_test.py

Support metadata in emitters and optimizers.
(this is part of a series of PRs to address #87; see #114)

Add metadata to emitters and optimizers

---

ribs/optimizers/_optimizer.py
tests/core/emitters/emitter_base_test.py
tests/core/optimizers/optimizer_test.py

The optimizer was previously not passing metadata to emitters. This PR fixes that.
(Include this as part of the metadata PRs)

Fix bug with optimizer metadata

---

examples/tutorials/arm_repertoire.ipynb
examples/tutorials/fooling_mnist.ipynb
examples/tutorials/lsi_mnist.ipynb
examples/tutorials/lunar_lander.ipynb

(title)
Add bibtex citations for tutorials (#122)

Add bibtex citations for tutorials

---

examples/lunar_lander.py
examples/sphere.py
ribs/archives/_add_status.py
ribs/archives/_archive_base.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/emitters/opt/_cma_es.py
ribs/optimizers/_optimizer.py
ribs/visualize.py

Fixed vocabulary and grammar in various places.
Fix vocab in various areas (#138)

Fix vocab in various areas

---

ribs/archives/_archive_base.py
ribs/archives/_sliding_boundaries_archive.py
tests/archives/archive_base_test.py

The clear() method removes all elites from the archive. Resolves #134
Add clear() method to archive (#140)

Add clear() method to archive

---

tests/archives/archive_base_test.py
tests/archives/conftest.py
tests/archives/cvt_archive_test.py
tests/archives/grid_archive_test.py
tests/archives/sliding_boundaries_archive_test.py
tests/optimizers/optimizer_test.py

More vocabulary fixes - replacing "entry" with "elite" and (sometimes) "solution."
Replace "entry" with "elite" in tests (#144)

Replace "entry" with "elite" in tests

---

ribs/archives/_archive_base.py

An uninitialized archive cannot be cleared.
(followup to #140)

Require initialization for archive.clear()

---

examples/tutorials/lunar_lander.ipynb

Just a small fix since tests failed on master.
(exclude from changelog)

Fix lunar lander notebook

---

docs/_templates/sourcelink.html

Resolves #162
Fix Colab links in stable docs (#164)

Fix Colab links in stable docs

---

ribs/archives/_archive_data_frame.py
tests/archives/archive_data_frame_test.py

Fixes to the documentation for `as_pandas`. We also found some minor bugs (see TODO list).
(add to description for #158)

Fixes for as_pandas

---

HISTORY.md
ribs/__init__.py
setup.cfg
setup.py

Release PR for 0.4.0.
(exclude)
See https://docs.pyribs.org/en/latest/contributing.html#deploying

v0.4.0 release

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
HISTORY.md

From now on, changelogs will be updated in the PR itself, so that we do not have to manually track it somewhere else. During release, we can copy the changelog from `HISTORY.md` into the GitHub release.

Add procedure for updating changelog

---

HISTORY.md
docs/conf.py
setup.py

Upgrade Sphinx docs dependency.

Sphinx Dependency Upgrade

---

HISTORY.md
ribs/visualize.py

fix typo and formatting in `ribs/visualize.py`

fix typo and formatting in `ribs/visualize.py`

---

.github/workflows/testing.yml
HISTORY.md

This is useful for making sure we did not break the documentation, as the documentation contains several code examples which Sphinx executes.
Originally, we considered linking ReadTheDocs with our checks, but building it in a job is much simpler.

Build docs during CI/CD workflow

---

HISTORY.md
ribs/archives/_archive_base.py
tests/archives/archive_base_test.py

Will implement `elites_with_measures_single` in a followup PR.

Replace elite_with_behavior with batched elites_with_measures method in archives

---

docs/api/ribs.emitters.rankers.rst

Forgot to add `emitters.rankers.rst`

add sphinx file

---

HISTORY.md
ribs/emitters/rankers.py
tests/emitters/rankers_test.py

return ranking_values from ranker

return ranking_values from ranker

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Miscellaneous text updates

---

README.md

Add the list of users, publications, and software using pyribs.

Add user list to README

---

tests/archives/grid_archive_test.py

Test zero length for add

---

HISTORY.md
ribs/archives/_archive_base.py
tests/archives/archive_base_test.py

A convenient way to access the best elite in an archive.

Add best_elite property for archives

---

README.md

Update pyribs citation with new authors

---

setup.py

Newer versions of pylint seem to have issues with our configuration.

Fix pylint version so that it works with our config

---

HISTORY.md
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_iso_line_emitter.py
tests/emitters/emitter_base_test.py

specify that `x0` is 1-dimentional for all emitters

---

HISTORY.md
ribs/emitters/_evolution_strategy_emitter.py

Expose emitter.restarts as a property

Expose `emitter.restarts` as a property.

---

HISTORY.md
ribs/archives/_add_status.py
ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/emitters/_gradient_aborescence_emitter.py
ribs/visualize.py
tests/archives/archive_base_test.py
tests/archives/conftest.py
tests/archives/cvt_archive_test.py
tests/archives/grid_archive_test.py
tests/archives/sliding_boundaries_archive_benchmark.py
tests/archives/sliding_boundaries_archive_test.py

Rename fields and update documentation in archive code

---

README.md
docs/api/ribs.schedulers.rst
docs/examples.md
docs/tutorials.md

Fix Scheduler docs

---

HISTORY.md
examples/sphere.py
ribs/emitters/__init__.py
ribs/emitters/_gradient_arborescence_emitter.py
tests/emitters/gradient_arborescence_emitter_test.py

Fix GradientArborescenceEmitter name

---

tests/visualize_test.py

Add input validation tests for ribs.visualize

---

HISTORY.md
ribs/emitters/_evolution_strategy_emitter.py

Seems like we left this out somewhere along the way.

Set default ranker in EvolutionStrategyEmitter

---

HISTORY.md
docs/api/ribs.emitters.opt.rst
docs/index.md
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/opt/__init__.py
ribs/emitters/opt/_adam_opt.py
ribs/emitters/opt/_evolution_strategy_base.py
ribs/emitters/opt/_gradient_ascent_opt.py
ribs/emitters/opt/_gradient_opt_base.py

Make ribs.emitters.opt public

---

ribs/emitters/rankers.py

Minor error encountered in the documentation.

Fix references to add

---

HISTORY.md
setup.py

Based on https://github.com/Farama-Foundation/Gymnasium/blob/main/pyproject.toml.

Add back the “all” extra like gymnasium does

---

README.md

Rearrange README sections

---

README.md

Add Paul Kent to users

---

tutorials/arm_repertoire.ipynb

Remove unused variable in Arm tutorial

---

ribs/visualize.py

Simple error discovered while looking thru documentation.

Fix colorbar links

---

ribs/emitters/_gradient_arborescence_emitter.py

Add gradient arborescence details to docstring

---

Makefile
setup.py

Upgrade sphinx-autobuild

---

HISTORY.md
Makefile
ribs/__init__.py
setup.cfg
setup.py
tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/lunar_lander.ipynb
tutorials/tom_cruise_dqd.ipynb

Release PR for v0.5.0. Follows current instructions in CONTRIBUTING.md

Release v0.5.0

---

tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/lunar_lander.ipynb
tutorials/tom_cruise_dqd.ipynb

Normal part of the release process.

Revert tutorial links to latest

---

HISTORY.md
ribs/archives/_cvt_archive.py

Typo: tesselation -> tessellation

---

HISTORY.md
README.md
ribs/__init__.py
setup.cfg
setup.py
tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/lunar_lander.ipynb
tutorials/tom_cruise_dqd.ipynb

v0.5.1 of pyribs features miscellaneous documentation edits. This PR is part of the deployment steps described in CONTRIBUTING.

Release v0.5.1

---

ribs/emitters/_gradient_arborescence_emitter.py

Fix link to GradientOptBase

---

ribs/archives/_cvt_archive.py

Small note to memorialize our choice of scipy's k-D tree over sklearn's k-D tree.

Add note about k-D tree implementation

---

HISTORY.md
README.md
ribs/archives/_cvt_archive.py
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
tutorials/lunar_lander.ipynb

Miscellaneous documentation fixes

---

HISTORY.md
ribs/emitters/_gradient_arborescence_emitter.py
tests/emitters/gradient_arborescence_emitter_test.py

Raise error messages when ask is called without ask_dqd

---

HISTORY.md
ribs/__init__.py
setup.cfg
setup.py
tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/lunar_lander.ipynb
tutorials/tom_cruise_dqd.ipynb

Release v0.5.2

---

HISTORY.md
setup.py

Update Distribution Dependencies

---

tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/lunar_lander.ipynb
tutorials/tom_cruise_dqd.ipynb

Revert tutorial links to lastest

---

HISTORY.md
setup.py

CONTRIBUTING.md was amended in #351 to state that we install pre-commit in the dev dependencies, but we forgot to modify the dependencies in #351.
`HISTORY.md`

Add pre-commit to dev deps

---

HISTORY.md
ribs/visualize/__init__.py
ribs/visualize/_cvt_archive_heatmap.py
ribs/visualize/_grid_archive_heatmap.py
ribs/visualize/_sliding_boundaries_archive_heatmap.py

Miscellaneous edits to the examples in the visualization docs.
`HISTORY.md`

Improve visualization docs examples

---

HISTORY.md
README.md
ribs/__init__.py
setup.cfg
setup.py
tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/lunar_lander.ipynb
tutorials/tom_cruise_dqd.ipynb

v0.6.0 features various visualization upgrades. This PR is part of the deployment steps described in CONTRIBUTING.
`HISTORY.md`

Release v0.6.0

---

HISTORY.md
ribs/__init__.py
setup.cfg
setup.py
tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/lunar_lander.ipynb
tutorials/tom_cruise_dqd.ipynb

v0.6.1 fixes an installation bug in our tutorials. This PR is part of the deployment steps described in CONTRIBUTING.
`HISTORY.md`

Release v0.6.1

---

HISTORY.md
ribs/__init__.py
setup.cfg
setup.py

Following the new instructions in #382, the actual 0.6.2 release will happen on the `release/0.6.x` branch.
`HISTORY.md`

0.6.2 Release Preparations

---

HISTORY.md
ribs/__init__.py
setup.cfg
setup.py

Part of the release process in CONTRIBUTING.md.
`HISTORY.md`

Release v0.6.3

---

CONTRIBUTING.md

Small edit in CONTRIBUTING.md.
`HISTORY.md`

Fix branch in release instructions

---

HISTORY.md
tests/archives/array_store_test.py

Fix ArrayStore field_desc test

---

examples/sphere.py
ribs/_utils.py
ribs/archives/_transforms.py

Collection of small fixes. See TODO list for more info.
`HISTORY.md`

Miscellaneous Fixes

---

ribs/__init__.py
setup.cfg
setup.py

Release steps for v0.6.4.
`HISTORY.md`

Release v0.6.4

---

HISTORY.md
docs/tutorials.md

Forgot to add to the TOC in #433
`HISTORY.md`

Add scalable cma-mae tutorial to TOC

---

HISTORY.md
tutorials/lsi_mnist.ipynb

Small fixes such as unused imports and variables.
`HISTORY.md`

Tidy up LSI MNIST notebook

---

ribs/archives/_archive_base.py
ribs/archives/_array_store.py

More fixes to documentation.
`HISTORY.md`

Docs fixes

---

docs/whats-new.md

Since v0.7.0 makes many changes, I've added a separate page documenting all the new features, similar to what was done in v0.5.0.
`HISTORY.md`

Add what's new for v0.7.0

---

HISTORY.md
ribs/__init__.py
setup.cfg
setup.py

Part of standard release process.
`HISTORY.md`

Prep for 0.7.0 release

---

setup.py

More dependency pins to resolve Read the Docs errors.
`HISTORY.md`

Continue fixing Read the Docs errors

---

HISTORY.md
ribs/__init__.py
setup.cfg
setup.py

Preparation for release of v0.7.1.
`HISTORY.md`

Prep version 0.7.1 release

---

.github/workflows/install.yml

The installation job has been failing recently on Mac. Upgrading the miniconda setup should fix this.
`HISTORY.md`

Fix installation job issues

---

HISTORY.md
ribs/emitters/rankers.py
tests/emitters/rankers_test.py

This ranker ranks solutions based on the `"novelty"` field output by the `add()` method.
`HISTORY.md`

Add NoveltyRanker for novelty search

---

HISTORY.md
tests/visualize/proximity_archive_plot_test.py

Forgot to add these in #476 :)
`HISTORY.md`

Add tests for proximity archive plot

---

HISTORY.md
examples/sphere.py
tests/examples.sh

An experimental algorithm that combines a ProximityArchive with local competition with an EvolutionStrategyEmitter.
`HISTORY.md`

Add nslc_cma_imp to sphere example

---

HISTORY.md
docs/tutorials.md
tutorials/optuna.md

Created a short tutorial page explaining the Optuna integration.
`HISTORY.md`

Add tutorial page on Optuna integration

---

HISTORY.md
tutorials/tom_cruise_dqd.ipynb

- `csv` isn't used anywhere in the tutorial
- Noted that GradientArborescenceEmitter is using Adam
`HISTORY.md`

DQD tutorial edits

---

tutorials/qdhf.ipynb

Update citation to reflect that QDHF was published at ICML 2024.
`HISTORY.md`

Update QDHF citation

---

HISTORY.md
ribs/emitters/_genetic_algorithm_emitter.py

Previously was calling private attributes.
`HISTORY.md`

Call public attributes in GeneticAlgorithmEmitter

---

pyproject.toml

Had some leftover indents with 4 spaces. Switched to 2 spaces.
`HISTORY.md`

Fix indents in pyproject.toml

---

ribs/emitters/opt/__init__.py

Just rearranged some docs for `ribs.emitters.opt`
`HISTORY.md`

Edit ribs.emitters.opt documentation

---

ribs/archives/_archive_base_2.py
ribs/archives/_grid_archive.py

Added back IndexError to sample_elites in ArchiveBase. Fixed some docstrings and formatting in GridArchive.
`HISTORY.md`

Minor edits to new ArchiveBase and GridArchive

---

ribs/emitters/_emitter_base.py

Minor edit to EmitterBase docstring

---

ribs/emitters/opt/__init__.py

This should help make things a bit clearer.
`HISTORY.md`

Add headers to ribs.emitters.opt docs

---

ribs/_utils.py

Remove solution_batch from error msgs

---

README.md

Removed the `_batch` names and put `batch_size=36` in the EvolutionStrategyEmitter.
`HISTORY.md`

Update README example usage

---

HISTORY.md
ribs/_utils.py
ribs/archives/__init__.py
ribs/archives/_categorical_archive.py
tests/archives/archive_base_test.py
tests/archives/archive_threshold_update_test.py
tests/archives/categorical_archive_test.py
tests/archives/conftest.py
tests/archives/grid_archive_test.py

The CategoricalArchive supports QD domains where the measures are categorical variables, such as strings and potentially other objects.
`HISTORY.md`

Add CategoricalArchive

---

ribs/archives/_proximity_archive.py

Turns out the old UCF pages for the NS and NSLC papers no longer exist, so I switched them to WebArchive links.
`HISTORY.md`

Fix citation for NS and NSLC

---

docs/examples.md
docs/examples/bop_elites.md
docs/examples/cqd_score.md
examples/bop_elites.py
examples/sphere.py
ribs/emitters/_bayesian_opt_emitter.py

Miscellaneous updates to examples and related documentation.
`HISTORY.md`

Updates to examples

---

HISTORY.md
ribs/__init__.py

Part of standard release process.
See CONTRIBUTING.md for release process.
`HISTORY.md`

Prep for 0.8.0 release

---

HISTORY.md
ribs/__init__.py

Preparation for v0.8.1
`HISTORY.md`

Prep for v0.8.1

---

tests/archives/grid_archive_test.py
tests/schedulers/scheduler_test.py

Add test for Scheduler with CategoricalArchive

---

.github/workflows/testing.yml
HISTORY.md
README.md
pyproject.toml
tests/README.md
tests/conftest.py

Start Array API infrastructure

---

.github/workflows/testing.yml

Update CI comment

---

HISTORY.md
tutorials/qdaif.ipynb

Miscellaneous polishing for the tutorial.
`HISTORY.md`

Edits to QDAIF tutorial

---

tutorials/qdaif.ipynb

Pickle is not used here.
`HISTORY.md`

Remove unused import in QDAIF tutorial

---

HISTORY.md
pyproject.toml
ribs/schedulers/_bayesian_opt_scheduler.py
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/qdhf.ipynb
tutorials/tom_cruise_dqd.ipynb

Added more rules from Ruff; caught some more errors.

Add more lint rules from ruff

---

HISTORY.md
ribs/archives/_sliding_boundaries_archive.py
tests/archives/archive_base_test.py

Add best_elite back to SlidingBoundariesArchive

---

ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_scheduler.py

Small tweaks to the annotations.

Tweak scheduler annotations

---

ribs/archives/_archive_base.py

Add annotations to ArchiveBase. See #624

Annotate ArchiveBase

---

ribs/archives/_array_store.py

Fixed indentation.
- [N/A] I have added a description of my change to the changelog in `HISTORY.md`

Fix retrieve docstring

---

HISTORY.md
ribs/_utils.py
tests/archives/grid_archive_test.py

Resolves #613 by casting the objectives and measures when validating them.

Cast dtype when validating arguments
