icaros-usc/pyribs

ribs/optimizers/_optimizer.py
tests/core/optimizers/optimizer_test.py

Users were previously able to do something like:
```python
emitters = [GaussianEmitter(...)] * 5
optimizer = Optimizer(archive, emitters)
```
However, this is incorrect because `emitters` now contains 5 of the same instance of `GaussianEmitter`, when it should really contain 5 unique instances, which one would get if they instead did:
```python
emitters = [GaussianEmitter(...) for _ in range(5)]
```
This PR makes sure `Optimizer` cannot take in an `emitters` list where any of the members have the same `id()`.
Fixed a bug where Optimizer is able to take in non-unique emitter instances

Prevent Optimizer from taking in non-unique emitter instances

---

ribs/archives/_grid_archive.py
tox.ini

Add step in CI for checking test coverage, which requires disabling numba so that functions can be inspected. Found a bug with GridArchive not working when numba is disabled, so fixed that too.
Fixed a bug where GridArchive failed for float32 due to a small epsilon

Add coverage test and fix GridArchive epsilon bug

---

ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
tests/core/archives/grid_archive_test.py

Added clearer error messages for archives

Add clearer error messages for archives

---

.github/workflows/testing.yml

Add testing on Windows and MacOS. Due to concerns with runtime, only added tests for Python 3.7 for these OS's. We may add tests for 3.6 and 3.8 in the future. Resolves #72 
Added testing for Windows and MacOS (on Python 3.7 only) (#83)

Improve CI/CD

---

.github/workflows/testing.yml
Makefile
pytest_benchmark.ini
pytest_no_benchmark.ini
setup.cfg
tox.ini

Moved the benchmarks and coverage to a separate job in the CI so that it runs faster. We do not need to test benchmarks and coverage on all platforms, so we only run it on Ubuntu with Python 3.7.
(do not include)

Separate benchmarks and coverage from tests

---

ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
tests/emitters/conftest.py

By making get_index() public, we have a method that we can link to when we say "this is what the index for this archive means." Furthermore, it will be less awkward for users to override `get_index`, as they will not be overriding a private method.
Make get_index() public in archives to emphasize each index's meaning (#128)

Make get_index() public in archives to emphasize each index's meaning

---

examples/tutorials/arm_repertoire.ipynb
examples/tutorials/lunar_lander.ipynb
ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py
tests/archives/archive_base_test.py

Index can be useful, so this PR adds it to `get_random_elite()` and `elite_with_behavior()` in the archive. This also makes the methods consistent with the `data()` method.
Add index to get_random_elite() and elite_with_behavior() in archives (#129)

Add index to get_random_elite() and elite_with_behavior() in archives

---

examples/tutorials/fooling_mnist.ipynb
examples/tutorials/lsi_mnist.ipynb
tox.ini

We are running into some failures with tests. This PR should fix the problems.
Fix dependency issues in tests (#139)

Fix dependency issues in tests

---

docs/_templates/autosummary/class.rst
ribs/archives/_archive_base.py
tests/archives/archive_base_test.py
tests/archives/sliding_boundaries_archive_test.py

The iterator goes through all elites in the archive. Given this, it makes sense for len to be the number of elites in the archive. Resolves #124
Add len and iter methods to archives (#151)

Add len and iter methods to archives

---

ribs/archives/_archive_base.py
tests/archives/archive_base_test.py

Previously, I only counted calls to add() -- but it is possible to clear() and then add() again, which would change the archive. This PR detects that by having the state count calls to both clear() and add().
(followup to #151)

Detect more complicated changes in archive during iteration

---

ribs/archives/__init__.py
ribs/archives/_archive_base.py
ribs/archives/_archive_stats.py
tests/archives/archive_base_test.py

To separate the statistics from the archive and cut down on the number of archive attributes, this PR moves the statistics to an ArchiveStats namedtuple.
A note on performance: The following benchmark code showed 3.89e-7 sec to construct one ArchiveStats on my computer:
```python
import timeit
from ribs.archives import ArchiveStats
n = 1000000
print(timeit.timeit(lambda: ArchiveStats(0, 1.0, 2.0, 3.0, 4.0), number=n) / n)
``` 
Add statistics to archives (#100, #155)

Move archive statistics to namedtuple attribute

---

examples/tutorials/lunar_lander.ipynb

Resolves #160. Turns out we need to set up a virtual display for Python. I also added detection for Google Colab (basically, `try` to `import google.colab`) so that this code does not run on local notebooks.
Fix video display for lunar lander in Colab (#163)

Fix video display for lunar lander in Colab

---

ribs/archives/_archive_base.py
ribs/archives/_archive_stats.py
tests/archives/archive_base_test.py

Renamed the `elites` attribute of `ArchiveStats` to `num_elites` to make it more clear.
(include with #157)

Rename elites to num_elites in ArchiveStats

---

ribs/optimizers/_optimizer.py
tests/optimizers/optimizer_test.py

Add checks for the size of emitter_kwargs (when it is a list), as well as for the arrays passed to tell().
Add checks for optimizer array and list shapes (#166)

Add checks for optimizer array and list shapes

---

CONTRIBUTING.md
HISTORY.md
README.md
benchmarks/README.md
examples/tutorials/arm_repertoire.ipynb
examples/tutorials/lunar_lander.ipynb
ribs/visualize.py
setup.py
tests/examples.sh
tests/tutorials.sh

Several files still referred to the `ribs[all]` extra. This PR removes those references.
`HISTORY.md`

Update rest of repo to remove 'all' extra

---

.readthedocs.yml

readthedocs was failing to build since it still used the `all` extra instead of `visualize`
Exclude from changelog.

Fix readthedocs extras config

---

HISTORY.md
README.md
benchmarks/cvt_add.py
examples/lunar_lander.py
examples/sphere.py
ribs/archives/_archive_base.py
ribs/archives/_archive_stats.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/visualize.py
tests/archives/archive_base_test.py
tests/archives/conftest.py
tests/archives/cvt_archive_benchmark.py
tests/emitters/conftest.py

Papers such as [PGA-MAP-Elites](https://github.com/ollenilsson19/PGA-MAP-Elites), [MAP-Elites](https://arxiv.org/abs/1504.04909), [CMA-ME](https://arxiv.org/abs/1912.02400), [DQD](https://arxiv.org/abs/2106.03894), [DQD-RL](https://dqd-rl.github.io) all refer to the archive as consisting of _cells_ rather than _bins_. This PR replaces occurrences of bins with cells for consistency.
This does introduce breaking changes -- archives now take in `cells` rather than `bins`, and they have a `cells` property rather than a `bins` property.

Rename bins to cells for consistency with literature

---

HISTORY.md
ribs/archives/__init__.py
ribs/archives/_archive_base.py
ribs/archives/_elite.py
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_improvement_emitter.py
ribs/emitters/_iso_line_emitter.py
ribs/emitters/_optimizing_emitter.py
ribs/emitters/_random_direction_emitter.py
ribs/visualize.py
tests/archives/archive_base_test.py
tests/archives/archive_data_frame_test.py
tests/archives/cvt_archive_test.py
tests/archives/grid_archive_test.py

This PR adds an `EliteBatch` data structure for storing a batch of elites. This is similar to the `Elite` but stores a batch in each field rather than just one entry.
Since we added this new structure, we also renamed `Elite` to use the full word for each field name, and we replaced `behavior_values` with `measures` (we will make this latter change throughout the entire library later on).
Using the full word for each field (e.g. `objective` instead of `obj`) makes it clear what we are referring to -- for instance, we previously used words like `beh` and `meta` that were not necessarily well-known.
One issue to decide is how to name the fields in `EltieBatch`. I decided to go with `XXX_batch` rather than `batch_XXX` since `batch_XXX` would require making `XXX` plural, e.g. …

Add EliteBatch and rename fields in Elite

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_improvement_emitter.py
ribs/emitters/_iso_line_emitter.py
ribs/emitters/_optimizing_emitter.py
ribs/emitters/_random_direction_emitter.py
tests/archives/archive_base_test.py
tests/archives/cvt_archive_benchmark.py
tests/archives/grid_archive_benchmark.py
tests/archives/sliding_boundaries_archive_benchmark.py
tests/emitters/conftest.py

This PR replaces `get_random_elite` with a `sample_elites` method which samples an entire batch of elites from the archive rather than just a single elite. This allows the emitter to operate more quickly since they do not have to call `get_random_elite` one at a time. We have decided to rename the method so that we are guaranteed to break people who still use get_random_elite().

Replace get_random_elite() with batched sample_elites() method

---

HISTORY.md
docs/conf.py
setup.py

Add type hint rich linking and defaults to pyribs documentation

in-comment type hint rich linking and parameter defaults

---

.readthedocs.yml
HISTORY.md

The linking introduced in #204 was not showing up in the rendered docs on ReadTheDocs. Bumping the Python version to 3.8 seems to solve this.

Fix documentation rendering issues on ReadTheDocs

---

.pylintrc

Allow unlimited max-args in pylint since our classes may require many parameters. In the future, we may force users to only provide kwargs like scikit-learn does, so that the parameters are more readable.

Allow unlimited max args in pylint

---

HISTORY.md
ribs/archives/_archive_base.py
tests/archives/archive_base_test.py

Adds an `index_of_single` method for retrieving the index of measures for a single solution.
An alternative is to allow `index_of` to take in a 1D array of measures, but this complicates the implementation for users who wish to implement their own archives. By adding this extra method, users get `index_of_single` for free if they implement `index_of` correctly.
Furthermore, `index_of_single` makes it clear that users are choosing a method that is slow.

Add index_of_single method for getting index of measures for one solution

---

pinned_reqs/install.txt

Forgot to remove the `decorator` package from the pinned requirements when we removed it from `setup.py` in #200
- Exclude

Remove decorator from pinned reqs

---

HISTORY.md
ribs/_utils.py
ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
tests/archives/archive_base_test.py
tests/archives/grid_archive_test.py
tests/emitters/rankers_test.py

Raise ValueError for incorrect array shapes in archive methods

---

ribs/archives/_cvt_archive.py
setup.py

On python 3.9, `sklearn.cluster.kmeans` has deprecated `algorithm='full'`. According to the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html) for kmeans,
> "auto" and "full" are deprecated and they will be removed in Scikit-Learn 1.3. They are both aliases for "lloyd".
This deprecation has led to a warning for some users, and this changes resolves that warning.
- Exclude this from history

Fix `sklearn.cluster.KMeans` deprecation warning on Python 3.9

---

HISTORY.md
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_iso_line_emitter.py
ribs/emitters/opt/_cma_es.py

Batching the archive operations resulted in massive speedups for the library. Since numba tends to overcomplicate the implementation, we have decided to remove as much of it as we can. This does result in ~5s slowdown on the sphere example (e.g. with `cma_me_imp`, `cma_me_imp_mu`, and `map_elites`) but the total runtime is still much lower than before, and we gain much in code readability and hackability.
Note that we will continue to depend on numba (1) since numpy_groupies depends on it and (2) in case we need to speed up any other bottlenecks in the future.

Minimize numba usage

---

HISTORY.md
ribs/optimizers/_optimizer.py
tests/optimizers/optimizer_test.py

Added an `add_mode` parameter to the optimizer that allows adding solutions to the archive either in batch or one at a time. This makes it possible to recover the old pyribs behavior if so desired (although it is not recommended).

Allow adding solutions one at a time in optimizer

---

HISTORY.md
pinned_reqs/install.txt
ribs/emitters/opt/_cma_es.py
ribs/optimizers/_optimizer.py
setup.py

Previously, we placed threadpoolctl in the optimizer in order to force OpenBLAS to run with only one thread in CMA-ES. However, this meant that all emitters would be affected by OpenBLAS, including ones defined by users. This commit moves threadpoolctl out of the optimizer and into CMA-ES, so that we only limit OpenBLAS in our code.
In #51, we mentioned that moving threadpoolctl to CMA-ES failed due to the overhead of creating the context manager. The new decorator from threadpoolctl seems to resolve this.
Here are some approximate times from running the sphere example (`python examples/sphere.py cma_me_imp --dim 20` and `python examples/sphere.py cma_me_imp --dim 100`) with the different ways of calling threadpoolctl. Note that when threadpoolctl is disabled, the multithreading in …

Move threadpoolctl from optimizer to CMA-ES

---

HISTORY.md
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/rankers.py
setup.py
tests/emitters/evolution_strategy_emitter_test.py

Handle complex ranker initialization logic from evolution_strategy_emitter in `get_ranker()`.

Extract ranker initialization subroutine in emitter constructor to `get_ranker`

---

ribs/emitters/opt/_cma_es.py

In #240, we introduced a slight change to CMA-ES that resulted in buggy code -- in particular, we received warnings about nan values in sqrt in the tests. This PR reverts that bug.

Fix bug in CMA-ES introduced in #240

---

HISTORY.md
ribs/archives/_archive_base.py
tests/archives/grid_archive_test.py

We encountered a bug where after calling clear(), adding to the archive did not result in the correct statuses and values. This happens because we did not reset the thresholds when calling clear(), and since archive addition is based on crossing the thresholds, nothing was being added to the archive. This PR clears the thresholds to resolve this bug.

Reset thresholds when calling clear

---

HISTORY.md
examples/lunar_lander.py
examples/sphere.py
examples/tutorials/fooling_mnist.ipynb
ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/emitters/_emitter_base.py
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_gradient_aborescence_emitter.py
ribs/emitters/_iso_line_emitter.py
ribs/schedulers/_scheduler.py
tests/archives/conftest.py
tests/archives/sliding_boundaries_archive_benchmark.py
tests/archives/sliding_boundaries_archive_test.py
tests/emitters/conftest.py
tests/emitters/emitter_base_test.py
tests/emitters/evolution_strategy_emitter_test.py
tests/emitters/gaussian_emitter_test.py
tests/emitters/gradient_aborescence_emitter_test.py
tests/emitters/iso_line_emitter_test.py
tests/emitters/rankers_test.py
tests/schedulers/scheduler_test.py

Deprecate positional arguments in constructor of all objects.
This PR is inspired by:
- https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep009/proposal.html
- https://github.com/scikit-learn/scikit-learn/issues/15005
- https://scikit-learn.org/stable/whats_new/v0.23.html#enforcing-keyword-only-arguments
Everything in the constructors are now keyword arguments except for `archive` and `emitter` parameters.
Deprecate positional arguments in:
Fix code in:

Deprecate positional arguments in constructors

---

HISTORY.md
ribs/archives/_archive_stats.py

The stats no longer need to be a namedtuple since we dropped Python 3.6 support. As we add more fields to the namedtuple, it will also get messy if there are users who still unpack it.

Make ArchiveStats a dataclass

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/archives/_archive_stats.py
tests/archives/archive_base_test.py

Normalized QD score divides the QD score by the number of cells in the archive.
Merge #275 first.

Add normalized QD score to ArchiveStats

---

docs/conf.py
setup.py

Turned out this was due to an issue with the myst-nb configuration as described in https://github.com/executablebooks/MyST-NB/issues/441

Fix rendering of math in tutorial notebooks

---

HISTORY.md
ribs/emitters/opt/_cma_es.py

Fix issue with negative eigenvalue in CMA-ES covariance matrix (resolves #285)

Negative eigenvalue fix (#285)

---

ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py

Since the ES in these emitters is no longer limited to CMA-ES, these docstrings were inaccurate.

Replace CMA-ES with ES in emitter docstrings

---

ribs/archives/_archive_base.py
ribs/archives/_archive_stats.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
tests/archives/archive_base_test.py

There are many archives which have negative objective values, thus making it useful to have a QD score which normalizes the objective values before summing them. This PR addresses that.
This feature will also be useful in the lunar lander tutorial, where we have negative objective values.

Add QD score offset to archives

---

HISTORY.md
ribs/archives/_archive_base.py
tests/archives/archive_base_test.py
tests/archives/grid_archive_test.py
tutorials/arm_repertoire.ipynb
tutorials/lunar_lander.ipynb

`elites_with_measures` and `elites_with_measures_single` is a very long name. `retrieve` is much more succinct.
While the name may be more vague, we think this is okay because we review the method in the lunar lander tutorial. Furthermore, the usage makes the meaning very clear; e.g., `elite_batch = archive.retrieve(measures_batch)`.
We also considered the name `find` but `find` implies a search, which is not what this method is doing. This method is merely _retrieving_ the elite at a given cell, not searching the archive to find an elite with the given measures.

Rename elites_with_measures to retrieve

---

CONTRIBUTING.md
HISTORY.md
Makefile
tutorials/lunar_lander.ipynb

Previously, I used links to `stable` for documentation links in the notebook. However, it is better to use `latest` since this notebook will appear in the following places:
* GitHub, where it is on master branch and thus should reference the master branch documentation
* Colab, when opened from the latest version
At the same time, we need a version of the notebook with stable links for when users open from the stable version. This requires a script which will replace the links before documentation deployment.
Options for the script include:
* Integrate with Sphinx since that is what ReadTheDocs calls -- this involves making a callback like the following in `conf.py`
```
def replace_notebook_links(app, docname, source):
"""Replaces "latest" links with "stable" links in notebooks if …
```

Facilitate linking to latest version of documentation

---

.github/workflows/testing.yml
CONTRIBUTING.md
HISTORY.md
docs/examples.md
examples/README.md
examples/lunar_lander.py
examples/sphere.py
setup.py
tests/examples.sh

It seems troublesome to have to install dependencies for all examples with `ribs[examples]` when you only want to run a single example. Thus, this PR switches the dependencies to be associated with each script, much like the tutorials.

Remove examples extra in favor of individual example deps

---

docs/conf.py

We keep getting warnings like:
```
...../docs/tutorials/README.md: WARNING: document isn't included in any toctree
```
because README.md is in `docs/tutorials` due to symlinking but we do not want it in the documentation. We tried to change this in #316 but the warning still shows up. Since it does not break the build, we will leave this warning as is.

Remove README from docs exclude patterns as it does not help

---

HISTORY.md
ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_scheduler.py
tests/schedulers/scheduler_test.py

Solutions may not be inserted into the archive if the threshold_min is too high. This can lead to unexpected behavior. For instance, GaussianEmitter with an initial set of solutions will keep producing that same set of solutions, and archive metrics like `obj_max` will be `None`. We shouldn't throw an error when this happens as users may decide they want this, but a warning is nice.

Schedulers warn if no solutions are inserted into archive

---

HISTORY.md
examples/sphere.py
ribs/emitters/_gradient_arborescence_emitter.py
tests/emitters/gradient_arborescence_emitter_test.py

Solution space bounds remain an open problem for DQD algorithms, and it is unclear that our implementation will create the correct behavior. Thus, we are removing the bounds handling for the time being.

Remove GradientArborescenceEmitter bounds

---

examples/sphere.py
ribs/emitters/_gradient_arborescence_emitter.py

We originally had batch_size for DQD emitter include the solution returned by ask_dqd, i.e., if you want ask to return 36 solutions you need to put batch_size=37. We reverted this decision and now assume that ask_dqd only returns one solution, i.e., you will put batch_size=36 for the above example. This make the batch_size description between DQD and non-DQD emitters consistent.
However, at some point we must have forgot to change the docstrings according. This PR address that.
**Furthermore, I find that some configuration in sphere.py is not consistent with the original paper.** For example, the [CMA-MAE paper](https://arxiv.org/pdf/2205.10752.pdf) "select[s] a batch size $\lambda = 36$ following prior work" (Appendix A), while [this …

DQD Emitter batch_size description

---

HISTORY.md
ribs/visualize.py
tests/visualize/visualize_test.py
tests/visualize_qdax/visualize_qdax_test.py

Currently, cvt_archive_heatmap plots individual polygons via ax.fill . We can speed this up by instead using a [`PolyCollection`](https://matplotlib.org/stable/api/collections_api.html#matplotlib.collections.PolyCollection) to add all the polygons at once. This is similar to using a `PatchCollection` as shown here: https://matplotlib.org/stable/gallery/shapes_and_collections/patch_collection.html.
Benchmark for plotting a `CVTArchive` with 10,000 cells:
- Before: 14.9 sec
- After: 0.6 sec
I used the following code to benchmark the implementation:
```python
"""Driver for cvt heatmap experiments."""
import time
import fire
import matplotlib.pyplot as plt
import numpy as np
from ribs.archives import CVTArchive
from ribs.visualize import cvt_archive_heatmap
def main(n_cells=10000):
"""Creates …
```

Speed up 2D cvt_archive_heatmap by order of magnitude

---

ribs/archives/_cvt_archive.py
ribs/visualize/_parallel_axes_plot.py

Using setdefault is shorter than checking "if X not in kwargs..."
`HISTORY.md`

Use setdefault to handle default kwargs more cleanly

---

HISTORY.md
docs/_ext/github_links.py
docs/conf.py
ribs/archives/_archive_base.py
ribs/archives/_archive_stats.py
ribs/archives/_cvt_archive.py
ribs/visualize/_cvt_archive_heatmap.py

Adds two Sphinx roles to make it easier to link to GitHub PRs and issues in the documentation. Examples are:
```
:pr:`123` -> Links to PR 123
:issue:`123` -> Links to issue 123
```
References:
- https://doughellmann.com/posts/defining-custom-roles-in-sphinx/
- https://www.sphinx-doc.org/en/master/development/tutorials/helloworld.html
`HISTORY.md`

Add GitHub link roles in documentation

---

.github/workflows/testing.yml

setup-python and checkout are both at v4 now; the current version of setup-python (v2) was raising deprecation warnings in GitHub Actions. This PR upgrades both of these actions.
`HISTORY.md`

Update checkout and setup-python actions in CI

---

HISTORY.md
ribs/_utils.py
ribs/archives/_archive_base.py
ribs/archives/_sliding_boundaries_archive.py
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py

Currently, the argument validation utilities do not perform preprocessing on the arguments passed into them. However, every call of these utilities is prefaced with preprocessing (e.g., converting with asarray). This PR moves the preprocessing into the utilities. This should make it easier to handle argument validation as there is no longer a need to repeat preprocessing code.
`HISTORY.md`

Refactor argument validation utilities

---

HISTORY.md
tutorials/tom_cruise_dqd.ipynb

The imports for the DQD tutorial had some redundancies and unnecessary parts; for instance, CLIP could be installed directly with pip instead of cloning and then installing.
`HISTORY.md`

Simplify DQD tutorial imports

---

.github/workflows/testing.yml
HISTORY.md
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/tom_cruise_dqd.ipynb

Tutorials tend to take a lot of time. Splitting the CI into multiple jobs, one per tutorial, should make this faster. This also makes it easier to catch dependency errors in the tutorials; for instance, this PR revealed two tutorials were missing tqdm installation.
Since this does introduce many more jobs, we also cut back on regular test jobs, only running on 3.11 instead of 3.8-3.11. We do this as several other jobs like pin and benchmarks already run on Python 3.8, so it is less essential to test on 3.8 again. Furthermore, we have never found errors in only the intermediate versions (between lowest supported and highest supported).
`HISTORY.md`

Split tutorial CI into multiple jobs

---

tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/lunar_lander.ipynb
tutorials/tom_cruise_dqd.ipynb

This is part of the release process in CONTRIBUTING.md.
`HISTORY.md`

Revert tutorial links to latest

---

CONTRIBUTING.md
HISTORY.md

Misc fixes to docs.
`HISTORY.md`

Miscellaneous docs fixes

---

CONTRIBUTING.md
tutorials/lsi_mnist.ipynb
tutorials/tom_cruise_dqd.ipynb

Since the visualize extra is installed in the CI for the tutorials, we did not detect bugs where the tutorials needed ribs[visualize] but only installed ribs. This PR adds ribs[visualize] to the tutorials that need it and also makes a note in the "Adding a Tutorial" section of CONTRIBUTING.md.
`HISTORY.md`

Import ribs[visualize] in tutorials that need it

---

CONTRIBUTING.md
HISTORY.md

Pyribs roughly follows a trunk-based development model. Previously, for releases, we only released from the trunk (master branch). However, this does not work well if we need to perform a patch release while trunk already has several features implemented for the next release. This PR shifts to the [branch-based release model](https://trunkbaseddevelopment.com/branch-for-release/) where we create release branches for minor versions. If we need to release patches, we can cherry pick commits from trunk into the release branch and then push the patch release. We will use this to properly release 0.6.2, as 0.6.1 was released with features for 0.7.0 (namely, OMG-MEGA and OG-MAP-Elites).
`HISTORY.md`

Switch to a branch-based release model

---

.github/workflows/testing.yml
HISTORY.md
tutorials/fooling_mnist.ipynb

Previously, we always installed `ribs[visualize]` before testing tutorials. This led to uncaught bugs where some tutorials needed `ribs[visualize]` to be installed but did not install it -- namely, since we always installed `ribs[visualize]`, the tutorial could get by without installing `ribs[visualize]`. This led to bugs such as those in #379. To remedy this issue, this PR removes the default installation of `ribs[visualize]` in the tutorial CI.
Instead, the notebook now installs the local copy of pyribs on its own -- we do this by replacing, e.g., `pip install ribs[visualize]` with `pip install .[visualize]`. Note that it is not possible to leave this dependency as is (i.e., `pip install ribs[visualize]`) because the tutorial would pull from PyPI instead of the local copy. …

Test pyribs installation in tutorials

---

HISTORY.md
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py

`np.product` is deprecated in numpy 1.25.0 -- see https://github.com/numpy/numpy/pull/23314
This PR replaces our calls to `np.product` with `np.prod`.
`HISTORY.md`

Replace np.product with np.prod due to deprecation

---

.github/workflows/install.yml
HISTORY.md

To increase confidence in our installation process, this PR adds a job that installs pyribs from PyPI on a daily basis. The time chosen is 19:00 UTC, which is 11AM PST or 12PM PDT (daylight savings time dictates which one applies).
This job can also be triggered by pushing to the `schedule-install` branch.
`HISTORY.md`

Add cron job for testing installation

---

HISTORY.md
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/rankers.py

Fixed a couple of broken links that reference other objects in the documentation, particularly related to rankers.
Also changed the name of several private constants in the rankers docs to make pylint happy.
`HISTORY.md`

Fix broken cross-refs in docs

---

.pylintrc
HISTORY.md
ribs/archives/_cvt_archive.py
tests/archives/cvt_archive_test.py

Added chunking calculation option to CVT Archive
- CVTArchive brute force calculation fails (OOM) for 1e8 inputs or more whereas chunking succeeds
`HISTORY.md`

Use chunk computation in CVT brute force calculation to reduce memory usage

---

HISTORY.md
ribs/archives/__init__.py
ribs/archives/_array_store.py
tests/archives/array_store_test.py

The ArrayStore will be part of an upcoming archive refactor in pyribs.
`HISTORY.md`

Add ArrayStore data structure

---

HISTORY.md
ribs/archives/_array_store.py
tests/archives/array_store_test.py

Although we mostly use the field names as dict keys, which can take on any value, it may be useful in the future to be able to use fields as identifiers. For example, if we are using kwargs, it makes sense to be able to pass in a field name as `f(field1=[...])`, which is not possible if `field1` is an invalid identifier like `field foo` (note the space).
`HISTORY.md`

Make ArrayStore fields be valid identifiers

---

HISTORY.md
ribs/archives/_array_store.py
tests/archives/array_store_test.py

The current ArchiveBase uses int32 indices (the assumption being that we will never have to deal with more than INT_MAX archive cells). This PR makes ArrayStore use int32 indices to be consistent with ArchiveBase.
`HISTORY.md`

Make ArrayStore use int32 indices

---

.github/workflows/install.yml

We do not need to checkout the pyribs repo when testing installation, since we are only accessing PyPI and Conda.
`HISTORY.md`

Remove checkout from installation CI

---

HISTORY.md
ribs/archives/_array_store.py
tests/archives/array_store_test.py

This PR modifies ArrayStore as follows:
- Introduces a tuple return type to the retrieve and as_dict methods
- Renames as_dict to data()
- Removes `as_pandas()` in favor of `data(return_type="pandas")` and `retrieve(return_type="pandas")`
`HISTORY.md`

Make ArrayStore data methods more flexible

---

HISTORY.md
ribs/archives/_array_store.py
tests/archives/array_store_test.py

This property is a cached property. It takes some computation, but we only want to do it once since it never changes. Furthermore, we do not want to store it in the constructor since we would then need to worry about it when reconstructing in `from_raw_dict`.
`HISTORY.md`

Add field_desc property to ArrayStore

---

HISTORY.md
ribs/archives/_array_store.py

Since methods like retrieve() already return copies, there is no need to make the copies be readonly.
`HISTORY.md`

Remove readonly restriction on ArrayStore data

---

HISTORY.md
ribs/archives/_array_store.py
tests/archives/array_store_test.py

The field_desc property can provide a bit too much info on the ArrayStore; we may only want to see the list of fields. This PR provides such a property.
`HISTORY.md`

Add field_list property to ArrayStore

---

HISTORY.md
ribs/archives/_archive_base.py
tests/archives/archive_base_test.py

Previously, we popped the threshold from best_elite to maintain backwards compatibility. This PR adds the threshold back so that best_elite aligns with the other archive methods.
`HISTORY.md`

Include threshold in `archive.best_elite`

---

HISTORY.md
ribs/archives/_array_store.py
tests/archives/array_store_test.py

This adds a shortcut whereby a single array can be retrieved from an ArrayStore. For instance, `occupied, objective = store.retrieve("objective")`. This call also extends to the data method, e.g., `objective = store.retrieve("objective")`.
`HISTORY.md`

Support single fields in ArrayStore.retrieve

---

HISTORY.md
ribs/archives/_archive_base.py
tests/archives/archive_base_test.py

The overall goal of this PR is to make it easier to access the data contained in each archive.
`HISTORY.md`

Add field_list and data methods to archives

---

HISTORY.md
ribs/archives/_archive_base.py
tests/archives/archive_base_test.py
tutorials/arm_repertoire.ipynb
tutorials/lunar_lander.ipynb

Previously, we relied on sentinel values to indicate whether a given cell was occupied. Since it is entirely possible that users want to use these sentinel values in their fields, we now return a separate `occupied` array that indicates which cells are occupied.
Considerations:
- Chose not to support additional return types like tuple and pandas for now, as such flexibility is less essential in `retrieve`, and this feature can be added fairly easily later on
- We still set the sentinel values depending on the field type since it may be confusing to see arbitrary values for a given field without seeing the occupied array.
- the `threshold` field is now included in outputs from `retrieve()`
`HISTORY.md`

Return occupied booleans in retrieve

---

HISTORY.md
ribs/archives/_array_store.py
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/_gradient_operator_emitter.py

Previously, we were using `isinstance(x, (int, np.integer))`; however, we can be more general and succinct by using `isinstance(x, numbers.Integral)` (the `numbers` module is part of the standard library).
`HISTORY.md`

Use numbers types when checking arguments

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/archives/_sliding_boundaries_archive.py
ribs/visualize/_cvt_archive_3d_plot.py
ribs/visualize/_cvt_archive_heatmap.py
ribs/visualize/_grid_archive_heatmap.py
ribs/visualize/_sliding_boundaries_archive_heatmap.py
tests/archives/grid_archive_test.py
tests/visualize/conftest.py
tests/visualize/sliding_boundaries_archive_heatmap_test.py

Removes the `_batch` suffix from parameter names for add(), e.g., `solution_batch` just becomes `solution`. This change helps to make way for #421, where we support custom fields. With custom fields, it makes sense to just have the field name in the argument, e.g., `myfield`, rather than `myfield_batch`. Thus, this PR makes the current argument names consistent with this usage.
Furthermore, the names with `_batch` are rather verbose, as it is usually clear from context whether the data is batch or singular (i.e., our methods mostly take in batch data, and when they need single data, they are named with the `_single` suffix, e.g., `add_single`).
This change is not as likely to affect users, since most only deal with the scheduler and do not call the archive directly; furthermore, most who …

Remove `_batch` from archive add() parameter names

---

ribs/_utils.py
ribs/archives/_archive_base.py
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/_gradient_operator_emitter.py
ribs/emitters/_iso_line_emitter.py

There is currently a check called `check_1d_shape`; we can instead make it a general `check_shape` function to check arbitrary shapes.
`HISTORY.md`

Generalize check_1d_shape to check_shape

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/archives/_archive_data_frame.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/visualize/_cvt_archive_heatmap.py

Continuation of #422. Note that I still use measures_batch and other batch names inside of methods themselves when it is necessary to have clarity.
`HISTORY.md`

Remove batch name from remaining archive methods

---

HISTORY.md
ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_scheduler.py
tests/schedulers/scheduler_test.py

Similar to #422, this removes `_batch` from parameter names in the scheduler. Even here, in a part of the API that is frequently used, I still anticipate that it will not affect users much, since most will pass in arguments positionally rather than as keywords.
`HISTORY.md`

Remove `_batch` from scheduler tell() parameter names

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/archives/_array_store.py
ribs/emitters/_emitter_base.py
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/_gradient_operator_emitter.py
ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_scheduler.py
tests/archives/grid_archive_test.py
tests/schedulers/scheduler_test.py

This PR makes it possible to pass in custom data to schedulers and emitters. For instance, one can call
```python
scheduler.tell(objective, measures, my_data=[1,2,3], my_other_data=[4,5,6])
```
The same applies for tell_dqd, and also for emitter methods.
`HISTORY.md`

Support custom data fields in scheduler and emitters

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/archives/_sliding_boundaries_archive.py
ribs/emitters/_emitter_base.py
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/_gradient_operator_emitter.py
ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_scheduler.py
tests/archives/cvt_archive_test.py
tests/archives/grid_archive_test.py
tests/archives/sliding_boundaries_archive_test.py
tests/emitters/emitter_base_test.py
tests/emitters/evolution_strategy_emitter_test.py
tests/emitters/gradient_arborescence_emitter_test.py
tests/emitters/rankers_test.py

To make the, more flexible, add() methods now return add_info instead of separate status_batch and value_batch. This will make it easy to return more info in the future.
Correspondingly, emitters now take in add_info instead of separate status_batch and value_batch arguments, and calls to add() have been fixed in the schedulers.
`HISTORY.md`

Replace status and value with add_info

---

ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py

This PR uses SeedSequence to seed the optimizer in emitters, rather than drawing integers from the current RNG. The ideal method would be to use `rng.spawn` (https://numpy.org/doc/stable//reference/random/generated/numpy.random.Generator.spawn.html#numpy.random.Generator.spawn) to create a child RNG, but this feature is only in NumPy 1.25, which only supports Python 3.9+ (we use 3.8+).
`HISTORY.md`

Use NumPy SeedSequence in emitters

---

docs/api/ribs.emitters.operators.rst
docs/index.md
ribs/emitters/operators/__init__.py

`ribs.emitters.operators` now shows up in the docs.
`HISTORY.md`

Add ribs.emitters.operators to docs

---

HISTORY.md
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/opt/_cma_es.py
ribs/emitters/opt/_evolution_strategy_base.py
ribs/emitters/opt/_lm_ma_es.py
ribs/emitters/opt/_openai_es.py
ribs/emitters/opt/_sep_cma_es.py
tests/emitters/evolution_strategy_emitter_test.py
tests/emitters/gradient_arborescence_emitter_test.py

Previously, bounds were passed in to the ES's in the `ask` method. However, we never use dynamic bounds, so it makes more sense to simply pass in the bounds in the init, as is done in the emitters.
Also made some other small changes to clean up the ESs (see TODO list below).
While moving the bounds around is a backwards-incompatible change, I do not anticipate this will affect many people since the evolution strategies are mostly internal classes that are called by the emitters.
`HISTORY.md`

Move evolution strategy bounds to init

---

HISTORY.md
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/opt/_cma_es.py
ribs/emitters/opt/_evolution_strategy_base.py
ribs/emitters/opt/_lm_ma_es.py
ribs/emitters/opt/_openai_es.py
ribs/emitters/opt/_sep_cma_es.py
ribs/emitters/rankers.py

This PR adds the `ranking_values` argument to the tell() method in evolution strategies. This paves the way for #434, since pycma needs the ranking values to be passed into tell().
Note that I considered removing ranking_values from `check_stop` and instead forcing the ES to store its own ranking values like pycma does, but I do not think this is a necessary change.
This change is backwards-incompatible, but similar to #436, I do not think it will affect most users.
`HISTORY.md`

Add ranking values to evolution strategy tell method

---

HISTORY.md
examples/sphere.py

Added an `es` parameter to the sphere example. This makes it easier to experiment with different ES's.
`HISTORY.md`

Allow overriding ES in sphere example

---

HISTORY.md
ribs/archives/_cvt_archive.py
tests/archives/cvt_archive_test.py

The centroid methods in CVTArchive were not generating centroids according to the specifications, i.e., the centroids were not of the correct number, and the centroids were not within the correct bounds.
`HISTORY.md`

Fix alternative centroid methods

---

HISTORY.md
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
tests/emitters/evolution_strategy_emitter_test.py
tests/emitters/gradient_arborescence_emitter_test.py

Previously, passing a SeedSequence as a seed in EvolutionStrategyEmitter and GradientArborescenceEmitter threw an error because SeedSequence cannot be initialized from another SeedSequence. This PR adds checks for SeedSequence so that SeedSequence can be passed in as a seed in these two emitters. Note that in other emitters, the seed is passed directly to the default_rng(), which can handle SeedSequence as input.
`HISTORY.md`

Support seed=SeedSequence in emitters

---

HISTORY.md
ribs/archives/_cvt_archive.py
ribs/archives/_sliding_boundaries_archive.py
tests/archives/cvt_archive_test.py

Previously, SlidingBoundariesArchive updated the lower_bounds and upper_bounds but not the interval_size. CVTArchive did not have an interval_size property at all.
`HISTORY.md`

Fix interval_size in CVTArchive and SlidingBoundariesArchive

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
tests/archives/archive_threshold_update_test.py
tests/schedulers/scheduler_test.py

Resolves #446 
Resolves #445 (see my comment there about threshold_min)
`HISTORY.md`

Raise error when threshold_min is set but learning_rate is not

---

CONTRIBUTING.md
setup.py

Read the Docs had an error due to sphinxcontrib-applehelp. This PR also makes a note to check Read the Docs before deploying in the future.
`HISTORY.md`

Fix Read the Docs build error

---

HISTORY.md
examples/lunar_lander.py

Previously, the script retrieved solutions incorrectly due to the reordering of columns in archive.data() compared to archive.as_pandas().
`HISTORY.md`

Fix solution retrieval in lunar lander eval

---

HISTORY.md
examples/lunar_lander.py

Previously, we did not record the qd score metric like in the lunar lander tutorial, nor did we consider the qd score offset in the archive.
`HISTORY.md`

Add qd score to lunar lander example

---

.github/workflows/testing.yml
HISTORY.md

Seems setup-miniconda@v2 uses Node 16 which raises a deprecation warning in GitHub Actions. Upgrading to v3 since that seems to be available.
`HISTORY.md`

Upgrade setup-miniconda to v3 due to deprecation

---

CONTRIBUTING.md

Forgot to do this for 0.7.1 but will leave as is since it is relatively minor.
`HISTORY.md`

Add tutorial links to patch release instructions

---

README.md

Mac users may need to put quotation marks around their installation commands due to zsh interpreting the square brackets differently. This PR adds a note on that in the installation command.
We also have installation commands in other files like the examples, but I think adding the note here should cover most people. At any rate, we have not yet received any issues about this, so people seem to be figuring it out.
I also updated this on the website.
`HISTORY.md`

Note quotation marks for installation

---

HISTORY.md
ribs/_utils.py
ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_sliding_boundaries_archive.py
tests/archives/archive_base_test.py
tests/archives/grid_archive_test.py

Previously, dtype in the archive could only be a single value specifying the dtype for the solution, objective, and measures all at once. Now, it is allowed to be a dict specifying separate dtypes for each of these, e.g.,
```python
archive = GridArchive(
solution_dim=3,
dims=[10, 10],
ranges=[(-1, 1), (-2, 2)],
dtype={
"solution": object,
"objective": np.float32,
"measures": np.float32,
},
)
```
Comments:
- This PR is a followup to #470 which allowed expressing the different dtypes present in the archive.
- Emitters used the dtype of their archive, e.g., `archive.dtype`. Now, they choose a specific field's dtype to use. The emitters implemented thus far all choose `archive.dtypes["solution"]`, i.e., they have the same dtype as the solution. …

Allow specifying separate dtypes for solution, objective, and measures

---

HISTORY.md
ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_scheduler.py
tests/schedulers/scheduler_test.py

We are working on supporting diversity optimization algorithms such as novelty search (see #472). One difference from other algorithms is that such algorithms do not require objectives. However, the current API to Scheduler.tell() is:
```
tell(objective, measures, **fields)
```
i.e., it assumes objective and measures will be provided. This PR seeks to make it possible to call `scheduler.tell(measures)` in addition to the current `scheduler.tell(objective, measures)`.
There are a couple of use cases that the scheduler must satisfy:
1. QD optimization (i.e., current behavior should not break):
- Positional arguments: `scheduler.tell(objective, measures)`
- Keyword arguments: `scheduler.tell(objective=objective, measures=measures)`
- Mixed (a rather extreme case): `scheduler.tell(objective, …

Support diversity optimization in Scheduler.tell

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py

Removing this private attribute. It is confusing to allow usage of `_cells` because in UnstructuredArchive, the `cells` property will change over time while `_cells` is set to the initial capacity. When initially added, it was assumed that `_cells` would remain constant.
`HISTORY.md`

Remove `_cells` attribute from ArchiveBase

---

HISTORY.md
examples/sphere.py
tests/examples.sh

Add `ns_cma` to sphere example. Usage is `python examples/sphere.py ns_cma`. This is novelty search with CMA-ES, which is achieved with a `ProximityArchive` and an `EvolutionStrategyEmitter` that uses `NoveltyRanker`.
`HISTORY.md`

Add novelty search with CMA-ES to sphere example

---

HISTORY.md
ribs/archives/_proximity_archive.py
tests/archives/proximity_archive_test.py

Previously, we returned inf novelty when the ProximityArchive was empty. However, this can cause issues in code that expects ranking values to be finite values, such as in `CMAEvolutionStrategy.check_stop`. Functionally, this value works just as well as inf because it shows that the solutions had enough novelty to be added to the archive. Strictly speaking, since the archive is empty in this case, the novelty is undefined, so there are many values that would work.
`HISTORY.md`

Set novelty to the threshold when ProximityArchive is empty

---

.pylintrc
HISTORY.md
ribs/archives/_proximity_archive.py
tests/archives/proximity_archive_test.py

Support NSLC in the ProximityArchive. This involves modifying the `add` method in particular to compute local competition as well as value. It should be noted that the NSLC paper does not specify how replacement should be handled in the archive -- it would seem that the authors only use a regular novelty search archive. We have decided to implement a rule where if the solution is not novel enough for addition, it shall be compared to its nearest neighbor and added if it exceeds the objective value of its nearest neighbor.
`HISTORY.md`

Support novelty search with local competition in ProximityArchive

---

HISTORY.md
ribs/emitters/rankers.py
tests/emitters/rankers_test.py

Added the DensityRanker, which will be used with DensityArchive for Density Descent Search. Also did a tiny bit of refactoring by alphabetizing the names in `ribs.emitters.rankers`.
`HISTORY.md`

Add DensityRanker for density descent search

---

HISTORY.md
ribs/archives/_proximity_archive.py

Adds a new public `compute_novelty` method to `ProximityArchive` to allow computing the novelty and local competition scores of arbitrary measures, not just of solutions that are passed into `add`. Previously, the operations in this method were part of `add`.
Regarding API, I allow the `local_competition` argument to either be None or an array of objectives to use during the local competition computation. I also considered an API that passed in objectives separately to be a bit more consistent with the `add` API, eg, `compute_novelty(objective, measures, local_competition)` but it seemed clunky to always require calling `compute_novelty(None, measures)`.
`HISTORY.md`

Move novelty computation into a separate method

---

HISTORY.md
docs/conf.py

See https://about.readthedocs.com/blog/2024/07/addons-by-default/
`HISTORY.md`

Fix documentation conf for readthedocs deprecations

---

HISTORY.md
ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_scheduler.py

Minor clarifications to how the error messages work in the scheduler. In ask(), we aren't checking if tell() is called; we're just checking if another ask method was previously called.
`HISTORY.md`

Clarify errors in scheduler docstrings

---

.pre-commit-config.yaml
HISTORY.md

This ensures that yapf takes precedence over isort when formatting files.
`HISTORY.md`

Move yapf after isort in pre-commit

---

HISTORY.md
tests/visualize_qdax/visualize_qdax_test.py

Right now, when running `make tests` as described in `CONTRIBUTING.md`, the tests in `tests/visualize_qdax/` fail because qdax is not installed. Thus, this PR adds a check to see if `qdax` is installed and skips the tests if it is not.
Thanks @Tekexa for raising this issue!
`HISTORY.md`

Skip qdax tests if qdax not installed

---

HISTORY.md
ribs/schedulers/_bandit_scheduler.py
tests/schedulers/scheduler_test.py

Fixes the `BanditScheduler` class because it could sometimes have unexpected number of active emitters.
- activate emitters that were never used, if there are none, those that are expected to perform better
- deactivate least performing emitters first
`HISTORY.md`

Fix issue bandit scheduler

---

HISTORY.md
ribs/schedulers/_bandit_scheduler.py
tests/schedulers/scheduler_test.py

Currently, the BanditScheduler has an `emitters` attr that returns the `_active_arr` variable. This does not make much sense since BanditScheduler does not have `emitters` as input, and `_active_arr` gives `emitters` a different meaning from the `emitters` attribute of Scheduler.
Thus, this PR removes the `emitters` attr and instead adds `emitter_pool` and `active` to indicate the pool of emitters in the scheduler and which ones are currently active, respectively.
`HISTORY.md`

BanditScheduler: Add emitter_pool and active attr; remove emitters attr

---

HISTORY.md
docs/conf.py

The ReadTheDocs version selector does not seem to work anymore. I have added the version selector that comes with the Material theme: https://bashtage.github.io/sphinx-material/customization.html?highlight=version#version-dropdown
`HISTORY.md`

Add version selector to docs

---

HISTORY.md
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_genetic_algorithm_emitter.py
ribs/emitters/_iso_line_emitter.py
ribs/emitters/operators/__init__.py
ribs/emitters/operators/_gaussian.py
ribs/emitters/operators/_iso_line.py
ribs/emitters/operators/_operator_base.py
tests/emitters/genetic_algorithm_emitter_test.py

Clean up miscellaneous parts of the operator implementation and related emitters.
`HISTORY.md`

Tidy up operator implementation

---

ribs/archives/_archive_base.py

`as_pandas` was deprecated a while ago. This PR removes the method completely.
`HISTORY.md`

Remove as_pandas from ArchiveBase due to deprecation

---

HISTORY.md
ribs/emitters/_emitter_base.py

Previously, we used the `measures` dtype for the emitter bounds, but the emitter operates in _solution_ space.
`HISTORY.md`

Make emitter bounds dtype match solution dtype

---

HISTORY.md
ribs/archives/_archive_base.py
ribs/archives/_array_store.py
ribs/archives/_grid_archive.py

Previously, ArrayStore returned `pandas.DataFrame`. However, since we never use a regular `DataFrame`, I think it is alright to just return `ArchiveDataFrame`. This also makes it easier to implement `archive.data()` since we don't have to cast to ArchiveDataFrame.
`HISTORY.md`

Make ArrayStore.data return ArchiveDataFrame instead of DataFrame

---

HISTORY.md
ribs/archives/_proximity_archive.py
ribs/visualize/_proximity_archive_plot.py
tests/archives/archive_base_test.py
tests/archives/proximity_archive_test.py

Refactor ProximityArchive to use the new ArchiveBase.
`HISTORY.md`

Refactor ProximityArchive

---

HISTORY.md
ribs/_utils.py
ribs/archives/_array_store.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_proximity_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/archives/_utils.py
ribs/emitters/_gradient_operator_emitter.py
ribs/emitters/_iso_line_emitter.py
tests/archives/archive_base_test.py

Previously, we had a very roundabout way of creating numpy scalars with the `np_scalar` function. Instead, we can just make the archive dtypes always be scalar types -- see https://numpy.org/doc/stable/reference/arrays.dtypes.html and https://numpy.org/doc/stable/reference/arrays.scalars.html#arrays-scalars-built-in; note that scalar types differ from numpy dtypes. Since the archive dtypes are always scalar types, we can just call them on scalars to create new numpy scalars.
`HISTORY.md`

Remove `np_scalar` util by making archive dtypes be numpy scalar types

---

HISTORY.md
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_proximity_archive.py
ribs/archives/_sliding_boundaries_archive.py

Just rearranged some things so that the stats calculations are always done in the same order: best_elite, objective_sum, stats.
`HISTORY.md`

Tidy up stats calculations in archives

---

ribs/archives/_archive_base.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_proximity_archive.py
ribs/archives/_sliding_boundaries_archive.py

Shuffled around `field_list` and `dtype` to have same order as in ArchiveBase
`HISTORY.md`

Rearrange methods to be more consistent with ArchiveBase

---

HISTORY.md
ribs/archives/_density_archive.py
tests/archives/density_archive_test.py

Support using sklearn's KernelDensity in DensityArchive to provide more flexible options for KDEs.
`HISTORY.md`

Add kde_sklearn option to DensityArchive

---

HISTORY.md
examples/sphere.py
ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_bayesian_opt_scheduler.py
ribs/schedulers/_scheduler.py
tests/schedulers/scheduler_test.py
tutorials/cma_mae.ipynb
tutorials/scalable_cma_mae.ipynb
tutorials/tom_cruise_dqd.ipynb

Previously, `result_archive` could only be passed in to schedulers as a kwarg. However, it is such a common argument that I think it makes sense to allow passing it in as a positional argument. Thus, a Scheduler can be constructed as `Scheduler(archive, emitter, result_archive)` rather than `Scheduler(archive, emitter, result_archive=result_archive)`.'
`HISTORY.md`

Allow result_archive to be positional arg in schedulers

---

.github/workflows/testing.yml
HISTORY.md
README.md
ribs/archives/_array_store.py
tests/conftest.py

This PR supports CuPy via the Array API. At first I thought this might be challenging since CuPy has a different model of devices, i.e., it depends on context managers rather than passing in devices. However, array-api-compat seems to have solved these issues and made CuPy compatible in terms of devices. Here are some references that I looked at:
- https://github.com/data-apis/array-api-compat/pull/293
- https://github.com/data-apis/array-api-compat/blob/main/array_api_compat/cupy/_aliases.py
- https://docs.cupy.dev/en/stable/reference/array_api_functions.html#cupy.array_api.ones
`HISTORY.md`

Add CuPy support to ArrayStore via Array API

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/testing.yml
.pre-commit-config.yaml
.pylintrc
CONTRIBUTING.md
HISTORY.md
pyproject.toml

Ruff seems to be a highly popular tool for Python nowadays. I believe migrating to ruff would make pyribs just a bit more accessible for contributors.
A followup PR would run ruff to format the entire codebase.
In addition to formatting, ruff also supports linting. I believe it would also be great to migrate to ruff for linting since it is significantly faster than pylint, but this will require a separate PR.
Here is the info for setting up ruff in pre-commit: https://github.com/astral-sh/ruff-pre-commit
`HISTORY.md`

Migrate from yapf to ruff for formatting

---

HISTORY.md
examples/bop_elites.py
examples/lunar_lander.py
examples/sphere.py
ribs/_utils.py
ribs/archives/_archive_stats.py
ribs/archives/_array_store.py
ribs/archives/_categorical_archive.py
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_proximity_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/archives/_utils.py
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_gradient_operator_emitter.py
ribs/emitters/_iso_line_emitter.py
tests/archives/archive_base_test.py

Resolves #577. Previously, a lot of uses of the archives' `dtypes` assumed that `dtypes` were scalar types, rather than dtypes (see [here](https://numpy.org/doc/stable/reference/arrays.scalars.html) for more info). As such, calls like `archive.dtypes["objective"](qd_score_offset)` were used to convert scalar values into the relevant NumPy dtype. However, this call does not work with the regular NumPy dtypes because they are not callable. Instead, the call must be replaced with `np.asarray(qd_score_offset, archive.dtypes["objective"])` -- this creates a 0-D NumPy array that can be used just like any scalar.
This change helps prepare the library for Array API adoption in #570. Note that some other options were considered besides 0-D arrays, but it seems that 0-D arrays are the correct way …

Treat archive dtypes as regular dtypes rather than scalar dtypes

---

HISTORY.md
examples/lunar_lander.py
tests/examples.sh
tutorials/lunar_lander.ipynb

Update the dependencies for the lunar lander tutorial and example. Specifically, I loosened the gymnasium dependency to be `>=1.0.0` since lunar lander seems fairly stable. I also removed the old `importlib.reload` statement in the notebook as that no longer seems necessary. Finally, I updated the installation command in `examples.sh`.
Tested in local Conda environments with Python 3.10/3.11, and on Colab.
`HISTORY.md`

Update dependencies for lunar lander

---

HISTORY.md
docs/whats-new.md
docs/whats-new/v0.5.0.md
docs/whats-new/v0.7.0.md
pyproject.toml
ribs/archives/_proximity_archive.py
ribs/emitters/_bayesian_opt_emitter.py

We are seeing various warnings related to typos and other mistakes in the documentation. `sphinx-codeautolink` was also throwing many warnings; I upgraded it and the warnings seem to be gone now.
`HISTORY.md`

Fix documentation warnings

---

README.md

The alt text for the badge was missing. Noticed it when building the documentation as a man page with sphinx.
`HISTORY.md`

Add alt text for discord link in readme

---

Makefile
docs/conf.py
docs/whats-new/v0.5.0.md
pyproject.toml
ribs/archives/_array_store.py
tutorials/ns_maze.ipynb

I was experimenting with building the docs as a Latex file, since Sphinx provides the ability to build many different documentation formats. Most of the other formats like man pages, epub, dirhtml, singlehtml all work out of the box (although they need some tweaking to get the right appearance), while latex errors out due to a variety of issues. The TODO section below lists the steps I took to get it to mostly work. I think if we wanted this to work properly, it would be possible with a lot more polishing. I have decided to merge this PR since the steps here all seem to not affect the current code, with the exception of item 6 (commenting out the gif; I reverted this).
1. **Make all tables have a table body.** It appears that there is a sphinx transform that will throw an error like:
``` …
```

Proof of concept for building Latex docs

---

.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml
CONTRIBUTING.md
HISTORY.md
docs/conf.py
docs/whats-new.md
pyproject.toml
tutorials/arm_repertoire.ipynb
tutorials/cma_mae.ipynb
tutorials/fooling_mnist.ipynb
tutorials/lsi_mnist.ipynb
tutorials/qdaif.ipynb
tutorials/qdhf.ipynb
tutorials/scalable_cma_mae.ipynb
tutorials/tom_cruise_dqd.ipynb

Previously, we used isort to sort the imports and ruff to handle the rest of the formatting. This PR migrates to using ruff for the import sorting as well, which reduces the number of tools we depend on.
`HISTORY.md`

Replace isort with ruff import check

---

HISTORY.md
docs/conf.py
ribs/schedulers/_bandit_scheduler.py
ribs/schedulers/_bayesian_opt_scheduler.py
ribs/schedulers/_scheduler.py
tests/schedulers/scheduler_test.py

Add type annotations to `ribs.schedulers`

---

pyproject.toml
ribs/visualize/_cvt_archive_3d_plot.py
ribs/visualize/_cvt_archive_heatmap.py
ribs/visualize/_grid_archive_heatmap.py
ribs/visualize/_parallel_axes_plot.py
ribs/visualize/_proximity_archive_plot.py
ribs/visualize/_sliding_boundaries_archive_heatmap.py
ribs/visualize/_utils.py
ribs/visualize/_visualize_qdax.py

Adds [pydocstyle](https://docs.astral.sh/ruff/rules/#pydocstyle-d) to the list of linting rules from Ruff. Since this triggers a lot of errors, I have commented out this rule for now and decided not to address all errors in this PR. Instead, I will handle them as I work on annotations (see #606).

Add pydocstyle and tidy up ribs.visualize docstrings

---

HISTORY.md
tests/visualize/args_test.py

Found a bug in the tests where they did not catch the errors for invalid cbar and aspect args because the archives were incorrectly sized. I changed the tests to use `match` so that this does not slip through again.

Fix bug in ribs.visualize args tests

---

HISTORY.md
docs/api/ribs.typing.rst
docs/conf.py
docs/index.md
ribs/typing.py

This PR adds a small module called `ribs.typing` that holds convenient type aliases.

Add custom types in ribs.typing

---

HISTORY.md
ribs/archives/_archive_data_frame.py
tests/archives/archive_data_frame_test.py

Previously, when a field was not found in an ArchiveDataFrame, we would just return `None`. However, having a None value is not very useful and can lead to unexpected behavior. This PR instead raises a KeyError similar to what one would get if accessing an invalid column in a regular DataFrame.
This PR also adds some type annotations to ArchiveDataFrame.

Raise `KeyError` in `ArchiveDataFrame.get_field` when field not found

---

pyproject.toml
ribs/visualize/_visualize_qdax.py

Instead of  `typing.Any`, we can use ParamSpec. Since this is only available in Python 3.10+ and we support 3.9+, this PR also adds the typing_extensions dependency.

Specify args and kwargs for visualize_qdax

---

.github/workflows/testing.yml
.readthedocs.yml
docs/api/ribs.typing.rst
docs/conf.py
pyproject.toml
ribs/_utils.py
ribs/archives/_array_store.py
ribs/typing.py

Annotations for the ArrayStore. Since we support the Array API in the ArrayStore, this PR also creates types to make it easier to work with the Array API.
Regarding typing of `xp`, official types for Array API are coming soon: https://github.com/data-apis/array-api-typing It also seems there is an unofficial package here that gets the job done: https://github.com/34j/types-array-api We should install the official package once it is available and update the files in this PR accordingly. I added a note to the tracking issue #624.
```
if TYPE_CHECKING:
import torch
import cupy as cp
Array = np.ndarray
if TYPE_CHECKING:
Array = Union[np.ndarray, torch.Tensor, cp.ndarray]
```

Annotate ArrayStore and add types for Array API

---

ribs/_utils.py
ribs/archives/_array_store.py
ribs/archives/_density_archive.py
ribs/emitters/opt/_cma_es.py
ribs/emitters/opt/_lm_ma_es.py
ribs/emitters/opt/_openai_es.py
ribs/emitters/opt/_pycma_es.py
ribs/emitters/opt/_sep_cma_es.py
ribs/schedulers/_bandit_scheduler.py

Resolves #576 by removing the old `readonly` function and replacing it with calls to `arr_readonly`, which is designed to support multiple array API backends.

Remove old readonly util

---

docs/api/ribs.typing.rst
docs/conf.py
ribs/_utils.py
ribs/archives/_archive_base.py
ribs/archives/_array_store.py
ribs/archives/_categorical_archive.py
ribs/archives/_cqd_score.py
ribs/archives/_cvt_archive.py
ribs/archives/_density_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_proximity_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/archives/_utils.py
ribs/typing.py
ribs/visualize/_cvt_archive_heatmap.py
ribs/visualize/_grid_archive_heatmap.py
ribs/visualize/_sliding_boundaries_archive_heatmap.py
ribs/visualize/_utils.py
tests/archives/archive_base_test.py

Annotate remaining archives. We mostly assume things are still written in numpy, and will update later as Array API is added.

Annotate archives

---

HISTORY.md
docs/api/ribs.typing.rst
pyproject.toml
ribs/archives/_archive_base.py
ribs/archives/_categorical_archive.py
ribs/archives/_cvt_archive.py
ribs/archives/_density_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_proximity_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/archives/_utils.py
ribs/typing.py
tests/archives/archive_base_test.py
tests/archives/categorical_archive_test.py
tests/archives/conftest.py
tests/archives/density_archive_test.py
tests/archives/grid_archive_test.py
tests/emitters/evolution_strategy_emitter_test.py
tests/emitters/gradient_arborescence_emitter_test.py
tests/emitters/optimizer_test.py
tests/schedulers/scheduler_test.py
tutorials/qdaif.ipynb
tutorials/tom_cruise_dqd.ipynb

Resolves #638
- Mark `dtype` as deprecated
- Add `solution_dtype`, `objective_dtype`, and `measures_dtype`
- Add error if `dtype` is passed in
- Update dtype calls in ArrayStore

Replace `dtype` parameter in archives with `solution_dtype`, `objective_dtype`, and `measures_dtype`

---

.github/workflows/testing.yml
.readthedocs.yml
docs/api/ribs.typing.rst
ribs/typing.py

The listing was previously in the ribs.typing.rst file, and we had to maintain it manually. Now, we just use `automodule`. 
~~The downside to this is that generic type aliases (`SingleData`, `BatchData`, and `FieldDesc`) all do not show their values -- see the screenshot below where `Array` shows up as an alias but `SingleData` does not.~~
~~This seems to be because they are aliases of `dict`, which Sphinx does not recognize as type aliases. Sphinx does recognize `typing.Dict`, but `typing.Dict` is deprecated. It seems that Sphinx sees things using `dict` into attributes rather than data.~~
I found that the above error no longer happens if I upgrade to Python 3.12 instead of 3.10. Hence, this PR also updates the CI to use Python 3.12 when building the docs. …

Remove manual ribs.typing API listing and upgrade docs CI

---

ribs/emitters/rankers.py
ribs/visualize/_parallel_axes_plot.py
tests/emitters/rankers_test.py

Add types annotations to the rankers module. Resolves #618 by adding documentation for RandomDirectionRanker. Also modified some of the tests to align with the type checker.

Annotate rankers

---

HISTORY.md
ribs/_utils.py
ribs/emitters/_bayesian_opt_emitter.py
ribs/emitters/_emitter_base.py
ribs/emitters/_evolution_strategy_emitter.py
ribs/emitters/_gaussian_emitter.py
ribs/emitters/_genetic_algorithm_emitter.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/_gradient_operator_emitter.py
ribs/emitters/_iso_line_emitter.py
tests/emitters/emitter_base_test.py
tests/emitters/evolution_strategy_emitter_test.py
tests/emitters/gaussian_emitter_test.py
tests/emitters/genetic_algorithm_emitter_test.py
tests/emitters/gradient_arborescence_emitter_test.py
tests/emitters/gradient_operator_emitter_test.py
tests/emitters/iso_line_emitter_test.py
tests/emitters_pymoo/bayesopt_emitter_test.py

Previously, #649 deprecated the `bounds` parameter completely in the emitters. However, I searched around on GitHub and found that quite a few people do use it. In the interest of not breaking backwards-compatibility, I am adding back `bounds` and allowing specifying either `bounds` or `lower_bounds` and `upper_bounds`.
- Change docstring
- Change argument order

Allow specifying emitter bounds with `lower_bounds` and `upper_bounds`

---

.pre-commit-config.yaml
pyproject.toml
ribs/archives/_cvt_archive.py
ribs/archives/_grid_archive.py
ribs/archives/_proximity_archive.py
ribs/archives/_sliding_boundaries_archive.py
ribs/emitters/_gradient_arborescence_emitter.py
ribs/emitters/_gradient_operator_emitter.py
tests/archives/array_store_test.py
tests/emitters/emitter_base_test.py
tests/emitters/gradient_arborescence_emitter_test.py
tests/emitters_pymoo/bayesopt_emitter_test.py

Misc maintenance.
- [N/A] I have added a description of my change to the changelog in `HISTORY.md`

Upgrade to Ruff 0.13.0 and run wrap-docstrings
